nome = input('Olá, Qual é o seu nome?')
print('Olá ' + nome + ', é um prazer te conhecer!!')
idade = input('Qual sua idade ' + nome + '?')
peso = input('Legal. E qual o seu peso ' + nome + '?')
print('Muito bom! \n ' + 'Meu nome é Luciano Braga e criei este script em Python no curso do Gustavo Guanabara')
print('Agora sei que seu nome é ' + nome + ', sei também que sua idade é ' + idade + ' anos e seu peso é ' + peso + 'Kg')
